[DEFAULT]
# These are specific to newsbeuter_dangerzone
static_columns=120
save_directory=/home/steven/downloads
show_links=true
clean_links=false
show_images=false
# The remainder of this is the same format as agaetr.ini
# THIS IS LIVE, STEVEN
toot = /home/steven/.local/bin/toot
mastodon = StevenSaus@faithcollapsing.com
shaarli = /home/steven/.local/bin/shaarli
shaarli_configs = shaarli
wallabag = /home/steven/.local/bin/wallabag
yourls_api=7456cfebd4
yourls_site = https://s.faithcollapsing.com
rss_output_path = /home/steven/.local/share/agaetr/output.xml
self_link = https://location.of.xml.example.com/output.xml
bluesky = /home/steven/apps/bsky-linux-0.0.73/bsky
pixelfed = ssaus@photos.faithcollapsing.com
smtp_server =
smtp_port =
smtp_username =
smtp_password =
email_from =
email_to =
waybackpy = /home/steven/.local/bin/waybackpy
archiveis = /home/steven/.local/bin/archiveis
ArchiveLinks = ignore
daily_posts = /home/steven/.local/share/agaetr/
gotumblr = /home/steven/sourcecode/gotumblr/gotumblr_ss.go
textmd = /home/steven/sourcecode/gotumblr/text.md
picgo = /usr/local/bin/picgo
TUMBLR_BLOG_NAME=stevensaus
TUMBLR_CONSUMER_KEY=TpAUYX5znBjcmJGJ3FmzOSxFSSzL3NpDp2TP44ttqhOJJ0hlG7
TUMBLR_CONSUMER_SECRET=mp7tV8WnLIMbMcpa18EQG7GtnRlpVX3a0yhmEmk3adglRUZesH
TUMBLR_OAUTH_TOKEN=QtfyDodAPj2VP2lUD5m9CiyUHiYcXbqYw7OYfrrtJdquah8wL2
TUMBLR_OAUTH_TOKEN_SECRET=2Fc4WLYW4UM7E6j50nF0MXy8Tz8zYdWoDtPSPepLKefQ4732LZ
