[DEFAULT]
# These are specific to newsbeuter_dangerzone
static_columns=
use_kitty=
save_directory=
enabled_out_dir=
show_links=
clean_links=
show_images=


# The remainder of this is the same format as agaetr.ini

toot = /app/bin/toot
mastodon = username@mastodon.example.com
bluesky = /path/to/bsky_sh_cli/bin/bsky
pixelfed = username@pixelfed.example.com
shaarli = /app/bin/shaarli
shaarli_configs = shaarli
wallabag = /app/bin/wallabag
yourls_api=
yourls_site =
rss_output_path = /full/path/to/agaetr/output.xml
self_link = https://location.of.xml.example.com/output.xml
smtp_server =
smtp_port =
smtp_username =
smtp_password =
email_from =
email_to =
waybackpy =
archiveis =
gotumblr = /path/to/gotumblr.go
textmd = /path/to/text.md
picgo = /path/to/picgo
TUMBLR_BLOG_NAME=blogname
TUMBLR_CONSUMER_KEY=see_readme_for_gotumblr
TUMBLR_CONSUMER_SECRET=see_readme_for_gotumblr
TUMBLR_OAUTH_TOKEN=see_readme_for_gotumblr
TUMBLR_OAUTH_TOKEN_SECRET=see_readme_for_gotumblr
