#!/bin/bash

##############################################################################
#  onews - a wrapper script to open newsboat with a cheatsheet
#  and leverage kitty, tmux, etc
#  (c) Steven Saus 2025
#  Licensed under the MIT license
#
##############################################################################

# The first argument, if any, should be profile, used to load different configs, environment files, etc.
# If the SECOND argument

LOUD=1
RELOAD=0
CLEAN=0
export calling_program="newsbeuter_dangerzone"

display_help () {
    echo "onews [--clean | --reload ] --profile [profile_name]"
    echo " "
    echo "if profile is omitted, falls back to default"
}


function loud() {
    if [ "${LOUD:-0}" -eq 1 ];then
        echo "$@"
    fi
}


###############################################################################
# Enter Here
###############################################################################


# parse command line options
#
while [ $# -gt 0 ]; do
    option="$1"
    case $option in
    --reload)
        RELOAD=1
        shift
        ;;
    --profile)
        shift
        profile="${1}"
        shift
        ;;
    --clean)
        CLEAN=1
        shift
        ;;
    --help)
        display_help
        exit
        ;;
    --loud)
        LOUD=1
        shift
        ;;
    *) shift ;;
    esac
done

# Set directories, get environment, etc.
export SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.local/state}/newsbeuter_dangerzone"
if [ ! -d "${CACHE_DIR}" ];then
    mkdir -p "${CACHE_DIR}"
fi
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/newsbeuter_dangerzone"
if [ ! -d "${CONFIG_DIR}" ];then
    loud "[WARN] NBDZ config directory does not exist; things may not work!"
    # If it doesn't exist, then just use defaults because NBDZ isn't set up
    enabled_out_dir="${SCRIPT_DIR}/out_enabled"
    save_directory="${HOME}/Downloads"  #  TODO - export all of these!
    NBConfigFile="${XDG_CONFIG_HOME/newsboat/config:-$HOME/.newsboat/config}" #default newsboat configuration
    NBCacheFile="${XDG_CONFIG_HOME/newsboat/cache:-$HOME/.newsboat/cache}" #default newsboat configuration
    NBLogFile="${XDG_CONFIG_HOME/newsboat/log:-$HOME/.newsboat/log}" #default newsboat configuration
    NBUrlsFile="${XDG_CONFIG_HOME/newsboat/urls:-$HOME/.newsboat/urls}" #default newsboat configuration
    profile=""
else
    PATH=$PATH:"${CONFIG_DIR}"  # <- newsbeuter_dangerzone script executables
    export PATH
    # if NBDZ is configured, but no profile is set, then it means default.
    if [ "${profile}" = "" ];then
        profile="default"
    fi
    loud "[info] Using profile ${profile}"
    # select profile-specific versions if they exist, otherwise use newsbeuter_dangerzone dir
    if [ -d "$(readlink -f "${CONFIG_DIR}/${profile}")" ] && [ "$profile" != "default" ];then
        # default is a special fallback case; so if someone doesn't put in a profile, it
        # automatically falls back to default, and then to ~/.newsboat if needed.
        my_CONFIG_DIR="${CONFIG_DIR}/${profile}"
        echo "$my_CONFIG_DIR"
    else
        my_CONFIG_DIR="${CONFIG_DIR}/default" # if you want, you can symlink this to ~/.newsboat
        if [[ ! -d "$(readlink -f "${CONFIG_DIR}/default")" ]]; then
            my_CONFIG_DIR="$HOME/.newsboat"
            if [[ ! -d "$(readlink -f ${my_CONFIG_DIR})" ]]; then
                mkdir -p "${my_CONFIG_DIR}"
            fi
        fi
    fi
    ConfigFile="${my_CONFIG_DIR}/newsbeuter_dangerzone.ini"
    NBConfigFile="${my_CONFIG_DIR}/config"  # Note that this is in newsbeuter_dangerzone's config directory, NOT newsboat's!
    NBCacheFile="${my_CONFIG_DIR}/cache"  # Note that this is in newsbeuter_dangerzone's config directory, NOT newsboat's!
    NBLogFile="${my_CONFIG_DIR}/log"  # Note that this is in newsbeuter_dangerzone's config directory, NOT newsboat's!
    NBUrlsFile="${my_CONFIG_DIR}/urls"  # Note that this is in newsbeuter_dangerzone's config directory, NOT newsboat's!
    static_columns=$(grep 'static_columns =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    use_kitty=$(grep 'use_kitty =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    save_directory=$(grep 'save_directory =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    enabled_out_dir=$(grep 'enabled_out_dir =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}') # TODO default to $profile/out_enabled
    show_links==$(grep 'show_links =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    clean_links==$(grep 'clean_links =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
fi

# I *hope* these get picked up by the subshell
export enabled_out_dir
export save_directory
export profile
export show_links
export my_CONFIG_DIR
export use_kitty
export calling_program

### Deal with clean and RELOAD
if [ "$CLEAN" != "0" ];then
        loud "[info] Cleaning database."
        newsboat --config-file="${NBConfigFile}" --cache-file="${NBCacheFile}" --log-file="${NBLogFile}" --url-file="${NBUrlFile}" -X --cleanup -x reload
        exit
fi
if [ "$RELOAD" != "0" ];then
        loud "[info] Reloading feeds. This may take a WHILE."
        newsboat --config-file="${NBConfigFile}" --cache-file="${NBCacheFile}" --log-file="${NBLogFile}" --url-file="${NBUrlFile}" -x reload
        exit
fi


# Reset image cache of current image URL
# This is a duplicate here so that it clears on startup
ImgCacheFile=${CACHE_DIR}/newsboat_img_links
echo "" > "${ImgCacheFile}"

# Are we in TMUX?
c_tmux=$(env | grep -c TMUX)
if [ $c_tmux -gt 0 ];then
    tmux rename-window news
    o_pane=$(tmux list-panes -F "#D")
fi


# added for kitty detection
if [ -S "/tmp/mykitty" ] && [ "$use_kitty" != "false" ];then
    loud "[info] kitty detected and being used."
    # running in kitty; the images will pop up in a window thanks to render_images.sh
    # https://dev.to/ajkerrigan/kitty-image-quality-in-the-terminal-without-giving-up-tmux-16be
    # So different sidebar layout needed
    if [ $c_tmux -gt 0 ];then
        if [ -f $(which tmux_topbar.sh) ];then
            tmux_topbar.sh -f 10 -h -b rich -w 90 -m "${CONFIG_DIR}/newsboat_cheatsheet_wide.md" --pager   # TODO - Need to remove absolute path here.
            side_pane=$(tmux list-panes -F "#D" | grep -v "$o_pane")
            tmux select-pane -t "$o_pane"
        fi
    fi
    if [ "$static_columns" != "" ];then
        COLUMNS=$static_columns
    else
        COLUMNS=$(tput cols)
    fi
    export COLUMNS
    #( /home/steven/.newsboat/renderer_images.sh ) &    # TODO - Need to remove absolute path here.     # separate because of kitty
    loud "[info] Loading newsboat."
    newsboat --config-file="${NBConfigFile}" --cache-file="${NBCacheFile}" --log-file="${NBLogFile}" --url-file="${NBUrlFile}"
    kitty @ --to unix:/tmp/mykitty send-text --match "title:^newsboat_image_display" $'\x1b[D'
else
    if [ $c_tmux -gt 0 ];then
        loud "[info] tmux detected and being used."
        if [ -f $(which tmux_sidebar.sh) ];then
            loud "[info] tdab detected and being used."
            #all this is pointless if the sidebar isn't possible
            # tmux, not kitty
            tmux_sidebar.sh -f 20 rich -w 60 -m "${CONFIG_DIR}/newsboat_cheatsheet_tall.md" --pager   # TODO - Need to remove absolute path here.
            side_pane=$(tmux list-panes -F "#D" | grep -v "$o_pane")
            # splitting sidebar for image preview
            tmux split-window -v -t 1 -p 60
            preview_pane=$(tmux list-panes -F "#D" | grep -v "$o_pane" | grep -v "$side_pane")
            # to make the renderer use the section width
            tmux select-pane -t "$preview_pane"
            tmux send-keys -t "$preview_pane" /home/steven/.newsboat/renderer_images.sh Enter     # TODO - Need to remove absolute path here.
            tmux select-pane -t "$o_pane"
        fi
    fi
    if [ "$static_columns" != "" ];then
        COLUMNS=$static_columns
    else
        COLUMNS=$(tput cols)
    fi
    export COLUMNS
    loud "[info] Loading newsboat."
    newsboat --config-file="${NBConfigFile}" --cache-file="${NBCacheFile}" --log-file="${NBLogFile}" --url-file="${NBUrlFile}"
    if [ $c_tmux -gt 0 ];then
        # remove tmux only preview pane
        tmux killp -t "$preview_pane"
    fi
fi
# removing any other panes if in tmux
if [ $c_tmux -gt 0 ];then
    tmux killp -t "$side_pane"
    tmux rename-window sh
fi
