#!/bin/bash

##############################################################################
#  onews - a wrapper script to open newsboat with a cheatsheet
#  (c) Steven Saus 2025
#  Licensed under the MIT license
#
##############################################################################

# The first argument, if any, should be profile, used to load different configs, environment files, etc.
# If the SECOND argument

LOUD=1
RELOAD=0
CLEAN=0
export calling_program="newsbeuter_dangerzone"

display_help () {
    echo "onews --loud [--clean | --reload ]"
    echo " "
}


function loud() {
    if [ "${LOUD:-0}" -eq 1 ];then
        echo "$@"
    fi
}


###############################################################################
# Enter Here
###############################################################################

loud "[info] Starting NBDZ"
# parse command line options
#
while [ $# -gt 0 ]; do
    option="$1"
    case $option in
    --reload)
        RELOAD=1
        shift
        ;;
    --clean)
        CLEAN=1
        shift
        ;;
    --help)
        display_help
        exit
        ;;
    --loud)
        LOUD=1
        shift
        ;;
    *) shift ;;
    esac
done

# Set directories, get environment, etc.
export SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Follows newboat paths
if [[ -d "$HOME/.newsboat" ]]; then
    CACHE_DIR="$HOME/.newsboat"
else
    CACHE_DIR="$HOME/.local/share/newsboat"
    mkdir -p "$CACHE_DIR"
fi

if [[ -d "$HOME/.newsboat" ]]; then
    CONFIG_DIR="$HOME/.newsboat"
else
    CONFIG_DIR="$HOME/.config/newsboat"
    mkdir -p "$CONFIG_DIR"
fi

ConfigFile="${CONFIG_DIR}/newsbeuter_dangerzone.ini"
if [ -f ${ConfigFile} ];then
    static_columns=$(grep 'static_columns =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    save_directory=$(grep 'save_directory =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    enabled_out_dir=$(grep 'enabled_out_dir =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    if [ "${enabled_out_dir}" = "" ];then
        enabled_out_dir="${CONFIG_DIR}/out_enabled"
    fi
    show_links==$(grep 'show_links =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
    clean_links==$(grep 'clean_links =' "${ConfigFile}" | sed 's/ //g' | awk -F '=' '{print $2}')
fi

# for now; focus on tmux
use_kitty="false"

# I *hope* these get picked up by the subshell
export enabled_out_dir
export save_directory
export show_links
export CONFIG_DIR
export calling_program


### Deal with clean and RELOAD
if [ "$CLEAN" != "0" ];then
        loud "[info] Cleaning database."
        newsboat -X --cleanup -x reload
        if [ $LOUD -eq 1 ];then
            notify-send "Completed clean"
        fi
        exit
fi
if [ "$RELOAD" != "0" ];then
        loud "[info] Reloading feeds. This may take a WHILE."
        newsboat -x reload
        if [ $LOUD -eq 1 ];then
            notify-send "Completed reload"
        fi
        exit
fi


# Are we in TMUX?
c_tmux=$(env | grep -c TMUX)
if [ $c_tmux -gt 0 ];then
    tmux rename-window news
    o_pane=$(tmux list-panes -F "#D")
fi
if [ $c_tmux -gt 0 ];then
    loud "[info] tmux detected and being used."
    if [ -f $(which tmux_sidebar.sh) ];then
        loud "[info] tdab detected and being used."
        #all this is pointless if the sidebar isn't possible
        # tmux, not kitty
        tmux_sidebar.sh -f 20 rich -w 60 -m "${CONFIG_DIR}/newsboat_cheatsheet_tall.md" --pager   # TODO - Need to remove absolute path here.
        side_pane=$(tmux list-panes -F "#D" | grep -v "$o_pane")
        # splitting sidebar for image preview
        tmux split-window -v -t 1 -p 60
        preview_pane=$(tmux list-panes -F "#D" | grep -v "$o_pane" | grep -v "$side_pane")
        # to make the renderer use the section width
        tmux select-pane -t "$preview_pane"
        tmux send-keys -t "$preview_pane" /home/steven/.newsboat/renderer_images.sh Enter     # TODO - Need to remove absolute path here.
        tmux select-pane -t "$o_pane"
    fi
fi
if [ "$static_columns" != "" ];then
    COLUMNS=$static_columns
else
    COLUMNS=$(tput cols)
fi
export COLUMNS
loud "[info] Loading newsboat."
newsboat
if [ $c_tmux -gt 0 ];then
    # remove tmux only preview pane
    tmux killp -t "$preview_pane"
fi

# removing any other panes if in tmux
if [ $c_tmux -gt 0 ];then
    tmux killp -t "$side_pane"
    tmux rename-window sh
fi
